### ISSUE TITLE
for transcription & collation, avoid  markup beyond `pb`,  `lb`, `p` and `unclear` 

### ISSUE THREAD

**Issue by csae8092** [Auden-Musulin-Papers/AMP-Musulin#3]
I expect any (semi)automatic collation will be easier with less markup, therefore something like below might not be necessary

https://github.com/Auden-Musulin-Papers/AMP-Musulin/blob/8b87981beab9928e83b265d408fe2ff443418ba9/data/tmp/amp-transkript__0001%20(copy).xml#L147

**Comment by timofruehwirth** [comment]
makes a lot of sense ... i have put this into a transcription_guidelines.txt in the amp-backbround repo
